### ISSUE TITLE
Getting an error message while trying to use Quill.

### ISSUE THREAD

**Issue by allengies** [MattConrad/Quill#12]
First of all, I like using Quill. It is a quick and easy way to get playtesters involved. Second, I have not had problems with it up until now.

Whenever I attempt to run my code to check for errors and create a permalink, I receive this error message; Could not find a part of the path '/home/quill/quillapp/AppData/RawInks/74318ead-b25b-4b89-a656-a1043286f2f5.ink'.

This applies no matter how much or how little, or even how simple, the code in question happens to be. (The other error I received happened owing to length of code, which was my fault.) Is there something I can do about this or is it on Quill's end?

**Comment by MattConrad** [comment]
This was an issue on Quill's end and it should be fixed now. Thanks for pointing it out, I admit I don't watch Quill that closely these days.
