### ISSUE TITLE
Add a share link at the end

### ISSUE THREAD

**Issue by aloisdg** [MattConrad/Quill#8]
Hello,

Can you add a way to get link with only the output of the script? A shareable link like the one in codepen would be perfect.

Thank you for Quill,
Cheers,

**Comment by MattConrad** [comment]
Probably can do something along these lines.

Thanks for the suggestion, it's a good idea.

**Comment by aloisdg** [comment]
You are welcome :)

**Comment by MattConrad** [comment]
Permalinks have been added, running on jeejah.xyz now. 

You will need to hit the Get Permalink button to get one. This button will show up upon a successful Play. (I didn't want to fill up the drive with files that nobody wanted to see.)

**Comment by aloisdg** [comment]
Perfect!
